name: portfolio
version: 1.0.0+1
publish_to: 'none'
description: Portfolio
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.1.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher_icon.png"
  remove_alpha_ios: true